title: Prediccion de la calidad del aire
downloads: true
description: Visualizacion, manejo y predicción del incremento de particulas contaminantes, en diferentes zonas de una ciudad a travez de datos reales proporcionados por codeGDL 
theme: jekyll-theme-cayman
