title: Prediccion de la calidad del aire
show_downloads: true
description: Visualizacion, manejo y predicción del incremento de particulas contaminantes, en diferentes zonas de la ciudad de Guadalajara a travez de datos reales proporcionados por codeGDL 
theme: jekyll-theme-cayman
